(function(z){
'use strict';var l7=function(a,b){a.Ja&&z.Cd(a.Ja,"u-hide",b)};var iga=function(a,b){a.Dx=b};var jga=function(a,b){z.Zt(a,7);var c=new z.Ct("",1,a.W());b.forEach(function(a){z.Vt(c,z.Bu(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);for(var d=z.wu(c),e=z.xu(c,d),g=0;g<d.length;g++){var h=e[g];if(h.length){for(var k={},m=[],q=0;q<h.length;q++){var t=h[q];k[z.B(t,"creatorIds")]=!0;m.push(t.getName())}h=d[g];q=g<d.length-1?d[g+1]:a.W().length;z.Vt(a,z.Bu(h,q,m,Object.keys(k)))}}};
var m7=function(a){return z.B(a,"replies")};var n7=function(a,b){for(var c=a.W(),d=b;" "==c[d];)d--;var d=c.lastIndexOf(" ",d)+1,e=c.indexOf(" ",d);-1==e&&(e=c.length);return{start:d,end:e,text:c.substring(d,e)}};var kga=function(a){return function(b,c){var d=n7(b,c);return d.text&&o7.test(d.text)?(z.cu(b,d.start,d.end),z.vu(b,a,d.start),d.start+a.length-c):0}};
var lga=function(a,b){var c=n7(a,b);z.$t(a,3,function(b){b.Wa()<=c.start&&b.Sa()>=c.end&&"token"==z.B(b,"rel")&&z.tu(a,z.ru(3,c.start,c.end))});c.text&&o7.test(c.text)&&z.Vt(a,z.eu(c.start,c.end,"/"+c.text,"","token"));return 0};var mga=function(a,b){z.YC(a,z.VC,z.hc(b,z.ec(!0)),void 0)};var p7=function(a){var b;b=String(a).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");return z.qr(a,z.tr)?(0,z.H)(b,z.rr(a)):b};
var q7=function(a,b,c){for(var d={},e=0;e<a.length;e++){var g=a[e],h=b.call(c,g,e,a);z.ba(h)&&(d[h]||(d[h]=[])).push(g)}return d};var r7=function(a,b,c){z.EA.call(this);if(!a)throw Error("Missing element for TemplateView");this.Ja=a;this.gi=b;this.Eu=c;this.AW="list"+z.na(this);this.ML=""};var s7=function(a,b){a.Ku=b;a.XC="note";a.La()&&t7(a);return a};var t7=function(a,b){var c=!!b;if(a.La()&&c)for(var c=a.gi.ad(),d=0;d<c.length;d++){var e=u7(a,c[d]);a.U("after-draw",c[d],e)}};
var v7=function(a,b){var c=a.ZL.call(null,b);return a.Ku?(a.Ku[a.XC]=c,c=z.Fy(a.Eu,a.Ku),delete a.Ku[a.XC],String(c)):String(z.Fy(a.Eu,c))};var w7=function(a,b){var c=a.Ja.querySelector("#"+x7(a,b));a.U("before-clear",b,c);c.innerHTML=v7(a,b);a.U("after-draw",b,c)};var u7=function(a,b,c){var d=window.document.createElement("div");d.className=a.ML;d.id=x7(a,b);d.innerHTML=v7(a,b);z.jf(a.Ja,d,"undefined"!=typeof c?c:a.Ja.children.length);return d};
var x7=function(a,b){var c=b.F(),d=b.D();if(!c||!d)throw Error("Unable to generate id "+b);return a.AW+c+d};var y7=function(a){this.Iq=a};var z7=function(a,b){return b?z.sz(a.Iq,b):null};var A7=function(a,b,c){mga(a.Iq,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})};var B7=function(a,b){return z.tf(a.Iq,b)?a.Iq:null};var C7=function(a,b){var c;c=B7(a,b);return(c=z.az(b,z.VC,c))&&c.getAttribute("name")||null};
var D7=function(a,b,c){(a=z.UC(c,B7(a,c)))&&z.Cd(b,"is-darkBackgrounded",z.ud(a,"is-darkBackgrounded"))};var E7=function(a){z.lY.call(this,a);this.sp=lga;this.Ts=kga;this.view=z.cP};
var F7=function(a,b,c,d,e){z.CJ.call(this,b);this.ca=a;this.Ea(new z.uI(c));this.Ea(new z.jL(!1));this.Ea(new z.oL);991<=window.innerWidth&&(this.vm=new E7(a),this.Ea(this.vm));this.Ea(new z.GJ);this.Ea(new z.hM(!1));this.Ea(new z.gI(d,!0));this.Gf=!0;this.mh=d;this.si=a.get("request");this.X=a.get("dialog");this.nX=e;this.O()};var G7=function(a){a.Qc(a.In);a.U("cancel")};var H7=function(a,b,c,d){F7.call(this,a,b,"Leave a note",400,d||null);this.Ga=c;this.L=a.get("routeBuilder")};
var nga=function(a,b,c){a.AC=b;a.pK=c.text;a.BC=c.image};var oga=function(a,b,c,d){a.PD=b;a.OD=c;a.xL=d};var I7=function(){return(0,z.H)("This note is only visible to the author, anyone @ mentioned, and publication editors (if any). The author or editors can choose to make it public.")};
var J7=function(a,b,c){b='\x3cdiv class\x3d"js-quotesList u-xs-hide"\x3e'+(a.jfa?"":z.M(z.NP({Sf:!0,title:"Highlights",od:(0,z.Q)(""+z.M(z.KP({href:(0,z.P)(""+z.O((0,z.Su)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:"Learn more",cc:!0},c)))})))+'\x3cul class\x3d"list list--quotes list--short '+(a.II.length?"":"is-empty")+'"\x3e';for(var d=a.II,e=d.length,g=0;g<e;g++){for(var h=d[g],k="",m=h.quotes,q=m.length,t=0;t<q;t++)k+=""+m[t].quoteId+(t!=q-1?",":"");k=z.L(k);
b+='\x3cli class\x3d"list-item list-item--inline" data-quote-ids\x3d"'+z.N(k)+'" data-quote-creator-id\x3d"'+z.N(h.user.userId)+'"\x3e'+z.M(z.ON(z.I(a,{user:h.user}),c))+"\x3c/li\x3e"}return(0,z.H)(b+"\x3c/ul\x3e\x3c/div\x3e")};
var pga=function(a,b,c){return(0,z.H)('\x3cdiv\x3e\x3cdiv class\x3d"buttonSet buttonSet--highlightMenu"\x3e'+z.M(z.PG({action:"quote",source:"quote_popover",icon:"icon--highlighter",S:"button--highlightMenu js-quoteAttributions-pileOn",zb:!0,vg:!0,mG:"quote",Ia:!0,La:a.La},c))+(c.variants.enable_quote_responses&&c.supportsEdit?z.M(z.RG({action:"quote-respond",source:"quote_popover",icon:(0,z.Q)(""+z.M(z.GG())),S:"button--highlightMenu",zb:!0,Ia:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"js-quoteAttributions-info quoteAttributions-info"\x3e'+
K7(a,0,c)+"\x3c/div\x3e\x3c/div\x3e")};var K7=function(a,b,c){b=z.H;a=a.k3?"Top highlight":(0,z.H)(z.M(z.eQ(z.I(a,{dI:!0,b5:!0}),c))+(1==a.Ce&&a.La?" highlighted":""));return b(a)};var qga=function(a,b,c){return(0,z.H)('\x3cdiv class\x3d"paragraphControls u-noUserSelect"\x3e'+L7(a,0,c)+"\x3c/div\x3e")};
var L7=function(a,b,c){b=z.H;var d='\x3cdiv class\x3d"notesMarker u-noUserSelect '+(0<a.zs&&0==a.Yj?" u-xs-hide":"")+'" data-action\x3d"select-anchor" data-action-value\x3d"'+z.N(a.Do)+'"\x3e'+M7(a,c)+"\x3c/div\x3e",e,g=""+(1==a.YP&&(a.ZA||a.lB)?a.ZA&&a.lB?" highlighted and commented":a.lB?" highlighted":a.ZA?" commented":"":""),g=z.L(g);e='\x3cspan class\x3d"paragraphControls-itemText paragraphControls-itemText--social"\x3e';c=""+z.M(z.eQ(z.I(a,{social:a.b3,La:a.ZA||a.lB,Ce:a.YP,dI:!0,p4:!0}),c))+
z.G(g);c=(0,z.Q)(c);e+=z.M(z.iQ(z.I(a,{text:c})))+"\x3c/span\x3e";a=(0,z.H)(e);return b(d+a)};
var M7=function(a,b){return(0,z.H)("remove"==a.Yj?'\x3cspan class\x3d"notesMarker-icon icon icon--notes"\x3e\x3c/span\x3e\x3cspan class\x3d"icon icon--remove"\x3e\x3c/span\x3e':a.Yj||a.zs?b.variants.enable_quotes&&b.variants.combined_margin_quotes&&0==a.Yj?'\x3cspan class\x3d"notesMarker-icon icon icon--quotes"\x3e\x3c/span\x3e\x3cspan class\x3d"notesMarker-count"\x3e'+z.G(a.zs)+"\x3c/span\x3e":'\x3cspan class\x3d"notesMarker-icon icon icon--notes"\x3e\x3c/span\x3e\x3cspan class\x3d"notesMarker-count u-showOnMobile"\x3e'+z.G(a.Yj)+
'\x3c/span\x3e\x3cspan class\x3d"notesMarker-count u-xs-hide"\x3e'+z.G(a.Yj+a.zs)+"\x3c/span\x3e":'\x3cspan class\x3d"notesMarker-icon icon icon--notesHollow"\x3e\x3c/span\x3e\x3cspan class\x3d"notesMarker-nocount"\x3e+\x3c/span\x3e')};
var rga=function(a,b,c){return(0,z.H)(z.M(z.OG({S:"button--dismissNotes",action:"dismiss-note",text:(0,z.Q)(""+M7({Yj:"remove"},c))},c))+'\x3cdiv class\x3d"notesList js-notesList"\x3e'+(c.variants.enable_quotes&&c.variants.combined_margin_quotes?z.M(J7({II:[]},0,c))+z.M(z.NP({title:"Notes",Sf:!0,T2:!0})):"")+'\x3cdiv class\x3d"notesItems"\x3e\x3c/div\x3e\x3cdiv class\x3d"newNoteEditor" tabIndex\x3d"-1"\x3e'+z.M(z.OG({S:"button--addNotes",action:"start-note",source:"new_note",zb:!0,title:"Leave a note",
text:(0,z.Q)('\x3cspan class\x3d"icon icon--addCircled icon--addNotes"\x3e\x3c/span\x3e\x3cspan class\x3d"notesAddText"\x3eLeave a note for \x3cspan class\x3d"js-notesPostCreator"\x3e\x3c/span\x3e\x3c/span\x3e\x3cspan class\x3d"notesAddCreatorText"\x3eLeave a note\x3c/span\x3e')},c))+(c.isAuthenticated?'\x3cdiv class\x3d"notesEditContainer is-notesEditMode"\x3e\x3cdiv class\x3d"notesAvatar"\x3e'+z.M(z.ON({Je:!0,user:c.currentUser},c))+'\x3c/div\x3e\x3cdiv class\x3d"notesAuthor"\x3e'+z.G(c.currentUser.name)+
'\x3c/div\x3e\x3cdiv class\x3d"notesItemEditor notesEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"notesFooter u-noUserSelect"\x3e'+z.M(z.OG({isPrimary:!0,UA:!0,S:"button--editNotesAction",action:"save-note",text:"Save"},c))+z.M(z.OG({S:"button--editNotesAction",action:"cancel-note",text:"Cancel"},c))+'\x3c/div\x3e\x3cdiv class\x3d"notesDisclaimer"\x3e'+z.M(I7())+"\x3c/div\x3e\x3c/div\x3e":"")+"\x3c/div\x3e\x3c/div\x3e")};
var sga=function(a,b,c){var d=a.note.author?a.note.author.userId:null;b='\x3cdiv class\x3d"notesItem-inner"\x3e\x3cdiv class\x3d"notesItem-main"\x3e'+('\x3cdiv class\x3d"notesControls"\x3e'+(a.Em?'\x3cul class\x3d"notesState notesState-dropdown" data-action\x3d"toggle-note-dropdown"\x3e'+("NEW"==a.note.state?'\x3cli\x3e\x3cspan class\x3d"icon icon--invisible"\x3e\x3c/span\x3ePrivate\x3cspan class\x3d"icon icon--notesStateDown"\x3e\x3c/span\x3e\x3c/li\x3e\x3cli data-action\x3d"approve-note" data-action-value\x3d"'+
z.N(a.note.noteId)+'"\x3e\x3cspan class\x3d"icon icon--group"\x3e\x3c/span\x3ePublic\x3c/li\x3e':"PUBLIC"==a.note.state?'\x3cli\x3e\x3cspan class\x3d"icon icon--group"\x3e\x3c/span\x3ePublic\x3cspan class\x3d"icon icon--notesStateDown"\x3e\x3c/span\x3e\x3c/li\x3e\x3cli data-action\x3d"unapprove-note" data-action-value\x3d"'+z.N(a.note.noteId)+'"\x3e\x3cspan class\x3d"icon icon--invisible"\x3e\x3c/span\x3ePrivate\x3c/li\x3e':"")+(a.DI.userId!=d?'\x3cli data-action\x3d"hide-note" data-action-value\x3d"'+
z.N(a.note.noteId)+'"\x3e\x3cspan class\x3d"icon icon--remove"\x3e\x3c/span\x3eDismiss\x3c/li\x3e':"")+"\x3c/ul\x3e":"PUBLIC"!=a.note.state?'\x3cul class\x3d"notesState"\x3e\x3cli data-tooltip\x3d"'+z.N(I7())+'"\x3e\x3cspan class\x3d"icon icon--invisible"\x3e\x3c/span\x3ePrivate\x3c/li\x3e\x3c/ul\x3e':"")+("PUBLIC"==a.note.state?'\x3cbutton data-action\x3d"show-note-permalink" data-action-value\x3d"'+z.N(a.note.anchor)+"-"+z.N(a.note.noteId)+'" class\x3d"notesLink icon icon--link" data-tooltip\x3d"Click to update the address bar with this note’s shareable link"\x3e':
"")+'\x3c/div\x3e\x3cdiv class\x3d"notesAvatar"\x3e'+z.M(z.ON({user:a.note.author},c))+'\x3c/div\x3e\x3cdiv class\x3d"notesAuthor"\x3e'+(d?'\x3ca href\x3d"/@'+z.N(a.note.author.username)+'" title\x3d"Go to the profile of '+z.N(a.note.author.name)+'"\x3e'+z.G(a.note.author.name)+"\x3c/a\x3e":"\x3ci\x3e"+z.G(z.BN())+"\x3c/i\x3e")+'\x3c/div\x3e\x3cdiv class\x3d"notesContent"\x3e'+p7(z.M(z.Dx(String(a.note.content))))+"\x3c/div\x3e"+(c.isAuthenticated?'\x3cdiv class\x3d"notesFooter u-noUserSelect"\x3e'+
(d==c.currentUser.userId?z.M(z.OG({S:"button--notesTextAction",action:"edit-note",actionValue:a.note.noteId,text:"Edit"},c))+z.M(z.OG({isPrimary:!0,UA:!0,S:"button--editNotesAction",action:"save-note",actionValue:a.note.noteId,text:"Save"},c))+z.M(z.OG({S:"button--editNotesAction",action:"cancel-note",actionValue:a.note.noteId,text:"Cancel"},c))+z.M(z.OG({S:"button--editNotesAction",action:"delete-note",actionValue:a.note.noteId,text:"Delete"},c)):"")+"\x3c/div\x3e":"")+"\x3c/div\x3e");var e=a.note.replies.length,
g=Math.max(a.note.replies.length-a.cn,0);if(e){b+='\x3cdiv class\x3d"notesReplies '+(0<g?"notesReplies--hidden":"")+'"\x3e\x3cdiv class\x3d"notesReplies-inner"\x3e';if(0<g){b+=z.M(z.OG({S:"button--hiddenNotesReplies",action:"show-hidden-note-replies",text:(0,z.Q)("View "+z.G(g)+(a.cn?" more":"")+(1<g?" replies":" reply"))},c))+'\x3cdiv class\x3d"notesReplies-container"\x3e';for(var h=a.note.replies,k=h.length,m=0;m<k;m++){var q=h[m];b+=m<g?N7(z.I(a,{Cf:q}),c):""}b+="\x3c/div\x3e"}h=a.note.replies;
k=h.length;for(m=0;m<k;m++)q=h[m],b+=m>=g?N7(z.I(a,{Cf:q}),c):"";b+="\x3c/div\x3e\x3c/div\x3e"}b+='\x3cdiv class\x3d"notesReplies-footer"\x3e'+(c.isAuthenticated?'\x3cdiv class\x3d"notesReply notesReply--creator is-notesEditMode"\x3e\x3cdiv class\x3d"notesAvatar"\x3e'+z.M(z.MN({user:c.currentUser},c))+'\x3c/div\x3e\x3cdiv class\x3d"notesAuthor"\x3e\x3ca href\x3d"/@'+z.N(c.currentUser.username)+'" title\x3d"Go to the profile of '+z.N(c.currentUser.name)+'"\x3e'+z.G(c.currentUser.name)+'\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d"notesReply-editor notesEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"notesFooter u-noUserSelect"\x3e'+
z.M(z.OG({isPrimary:!0,UA:!0,S:"button--editNotesAction",action:"save-reply",actionValue:a.note.noteId,text:"Save"},c))+z.M(z.OG({S:"button--editNotesAction",action:"cancel-reply",actionValue:a.note.noteId,text:"Cancel"},c))+"\x3c/div\x3e\x3c/div\x3e":"")+z.M(z.OG({isPrimary:!0,S:"button--notesReplyLink",action:"start-reply",source:"new_note_reply",actionValue:a.note.noteId,zb:!0,title:"Leave a reply",text:(0,z.Q)(""+(e||!a.note.author?"Reply to conversation":d==c.currentUser.userId?"Leave a reply":
"Reply to "+z.G(a.note.author.name)))},c))+"\x3c/div\x3e\x3c/div\x3e";return(0,z.H)(b)};
var N7=function(a,b){return(0,z.H)('\x3cdiv class\x3d"notesReply"\x3e'+(a.Em&&(null==a.Cf.author?null:a.Cf.author.userId)!=b.currentUser.userId?'\x3cdiv class\x3d"notesReply-hider" data-action\x3d"hide-reply" data-action-value\x3d"'+z.N(a.note.noteId)+","+z.N(a.Cf.replyId)+'" data-tooltip\x3d"Dismiss this reply"\x3e\x3cspan class\x3d"icon icon--remove"\x3e\x3c/span\x3e\x3c/div\x3e':"")+'\x3cdiv class\x3d"notesAvatar"\x3e'+z.M(z.MN({user:a.Cf.author},b))+'\x3c/div\x3e\x3cdiv class\x3d"notesAuthor"\x3e'+
(a.Cf.author?'\x3ca href\x3d"/@'+z.N(a.Cf.author.username)+'" title\x3d"Go to the profile of '+z.N(a.Cf.author.name)+'"\x3e'+z.G(a.Cf.author.name)+"\x3c/a\x3e":"\x3ci\x3e"+z.G(z.BN())+"\x3c/i\x3e")+'\x3c/div\x3e\x3cdiv class\x3d"notesContent"\x3e'+p7(z.M(z.Dx(String(a.Cf.content))))+"\x3c/div\x3e"+(b.isAuthenticated?a.Cf.author&&a.Cf.author.userId==b.currentUser.userId?'\x3cdiv class\x3d"notesFooter u-noUserSelect"\x3e'+z.M(z.OG({S:"button--notesTextAction",action:"edit-reply",actionValue:z.L(""+
a.note.noteId+","+(""+a.Cf.replyId)),text:"Edit"},b))+z.M(z.OG({isPrimary:!0,UA:!0,S:"button--editNotesAction",action:"save-reply",actionValue:a.Cf.replyId,text:"Save"},b))+z.M(z.OG({S:"button--editNotesAction",action:"cancel-reply",actionValue:a.Cf.replyId,text:"Cancel"},b))+z.M(z.OG({S:"button--editNotesAction",action:"delete-reply",actionValue:a.Cf.replyId,text:"Delete"},b))+"\x3c/div\x3e":"":"")+"\x3c/div\x3e")};
var tga=function(a){var b="";if(10<a.count)b+='\x3cdiv class\x3d"slideIndicator-fraction"\x3e1 of '+z.G(a.count)+"\x3c/div\x3e";else if(1<a.count){b+='\x3cul class\x3d"slideIndicators"\x3e';a=a.count;for(var c=0;c<a;c++)b+='\x3cli class\x3d"slideIndicator"\x3e\x3c/li\x3e';b+="\x3c/ul\x3e"}return(0,z.H)(b)};
var O7=function(a,b,c,d){z.EA.call(this);this.v0=a;this.hb=b;this.fc=null;this.zg=c;this.Ga=d;a=window.document.createElement("div");a.className="notesMarkers";z.hf(a,this.v0);this.Pn=a;this.kf={};this.cq=this.yq=null};
var P7=function(a,b){var c=Q7(a.hb,b),d=a.fc?R7(a.fc,b):[],e=c?c.rb():0,g=0,h=!1,k=!1,m={},q={};c.Dd(function(a){var b=a.eA();b&&((a=m7(a))&&a.forEach(function(a){g++;a.author&&(a.author.userId==z.Fj().userId&&(h=!0),a.author.social&&a.author.social.isFollowing&&(m[a.author.userId]=a.author))}),q[b.userId]=!0,b.userId==z.Fj().userId&&(h=!0),b.social&&b.social.isFollowing&&(m[b.userId]=b))});c=z.x.Oa();c.enable_quotes&&c.combined_margin_quotes&&d.forEach(function(a){a=a.user;q[a.userId]=!0;a.userId==
z.Fj().userId&&(k=!0);a.social&&a.social.isFollowing&&!m[a.userId]&&(m[a.userId]=a)});return{postId:a.Ga,Do:b,Yj:e+g,ZA:h,zs:d.length,lB:k,YP:Object.keys(q).length,b3:z.Db(m)}};
var S7=function(a,b,c){var d=a.zg.get(b);if(d){var e=a.kf[b];e&&(z.Cd(e,"is-active",c),c="left"==z.Vp(d,"float")?0:-1*z.lq(d,"margin").right,e.style.left=(767>=window.innerWidth||0!==c?c:10)+"px",a=z7(a.zg,b))&&(b=z.Pv(a.className),z.Cd(e,"is-notesSourceFloated",2==b||4==b),z.Cd(e,"u-hide",z.Zy(a,!1)),b=3==b,z.Cd(e,"is-notesSourceOutsetCenter",b),a=b||7==z.RC(a),z.Cd(e,"is-withoutSocialLine",a))}};
var uga=function(a){var b={};A7(a.zg,function(a,d){if(!(d in b)){var e;e=z.aq(a,this.Pn).y+z.mq(a).top;b[d]=e}},a);return b};var T7=function(a){var b=uga(a),c={};A7(a.zg,function(a,d){if(!c[d]){var h;if(this.kf[d])h=this.kf[d];else{h=P7(this,d);var k=z.Hy(qga,h);this.Pn.appendChild(k);if(0<h.Yj||0<h.zs)z.u(a,"is-withNotes"),z.u(k,"is-withNotes");h=this.kf[d]=k}h.style.top=b[d]+"px";S7(this,d,d==this.hb.Ta);c[d]=!0;D7(this.zg,h,a)}},a);for(var d in a.kf)c[d]||(z.kf(a.kf[d]),delete a.kf[d])};
var U7=function(a,b,c){z.CA.call(this);this.lM={};this.yL={};this.au={};this.gm=null;this.ca=a;this.si=a.get("request");this.L=a.get("routeBuilder");this.ga=a.get("modelStore");this.Ga=b;this.GM=0;this.Rl=c;this.NK=!1;this.Bg=null;this.Ta=""};var Q7=function(a,b){var c=a.lM[b];c||(c=a.lM[b]=new z.k1,a.U("new_note_list",c,a));return c};var vga=function(a){var b=z.Fj().userId;return a.sH().find(function(a){return a.Ih()==b})};
var wga=function(a,b){if(!b)return!1;var c=b.W();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Pa(a.content),"gi"),e=d.exec(c),c=e&&d.exec(c);return e&&!c?(c=a.endIndex-a.startIndex,a.startIndex=e.index,a.endIndex=e.index+c,a.content=e[0],!0):!1};var V7=function(a,b){b=z.pC(a.ga,b);Q7(a,b.tc()).add(b)};
var xga=function(a,b,c){var d=b.eb(),e=Q7(a,b.tc()),g=e?e.indexOf(b):-1,h=b.Sj();b.Uf(c);"HIDDEN"==c?a.ga.remove(b):b=z.pC(a.ga,b);var k=e?e.indexOf(b):-1;return{fe:a.si.put(z.w(a.L,z.iba,{postId:a.Ga,noteId:d}),{state:c},{json:!0}),AR:function(){b.Uf(h);-1==k&&(-1==g?e.add(b):e.Fj(b,g))}}};var yga=function(a,b,c){return a.si.put(z.w(a.L,z.lba,{postId:a.Ga,noteId:c,replyId:b}),{state:"HIDDEN"},{json:!0})};
var W7=function(a,b,c){this.range=a;this.anchor=b;this.Do=b.getAttribute("name");this.highlight=c};var X7=function(a,b,c,d,e){F7.call(this,a,b,"Leave a reply",200,d);this.L=a.get("routeBuilder");this.Ga=c;this.Iy=e||null};var Y7=function(a){z.ho.call(this);var b=z.wp();this.Gg=b&&new Z7(z.vq(b,!0),a);this.hj=b&&new Z7(z.vq(b,!1),a)};var Z7=function(a,b){this.Te=a;this.kV=b;var c=z.TC(a.node,b);this.rK=(this.yg=c)&&c.getAttribute("name");this.ay=c?z.uz(a,c):-1};
var $7=function(a){var b=window.document.body;return z.tf(b,a.Te.node)?a.Te:a.yg&&z.tf(b,a.yg)?z.vz(a.ay,a.yg):a.rK&&(b=z.sz(a.kV,a.rK))?z.vz(a.ay,b):null};
var a8=function(a,b,c){z.CA.call(this);this.vB=a;this.screen=a.get("screen");this.Ya=a.get("screenService");this.kG=a.get("app");this.ne=b;this.uN=this.ne.$a().clone();var d;(d=this.ne.$a().pi)&&d.subscribe(z.dZ,this.nL,this);this.Ad={};this.Gc=[];this.wG=a.get("butter-bar");this.Wu=a.get("dialog");this.qc=b=b.qc;this.RL=0;d=b.querySelector(".js-notesSource");this.anchors=new y7(d);var e=z.Ue("div","layoutSingleColumn notesPositionContainer");z.jf(this.qc,e,0);this.u4=e;e=window.document.createElement("div");
e.className="notesContainer";z.Gy(e,rga);this.u4.appendChild(e);this.Lf=e;this.Dz=b.querySelector(".js-postField");this.Ic=this.Lf.querySelector(".notesList");this.ln=z.gz(d);this.isAuthenticated=!!z.Hj();this.Em=c;this.data=new U7(a,this.ne.$(),this.ne.Rl);this.data.subscribe("new_note_list",this.uY,this);this.fc=null;if(this.Ao=a.get("voteWidget"))a=this.Ao,c=this.data,a.oE=c,a.La()&&(c=c.load(),z.p(z.id(z.XS(a),c),a.lK,a));this.Kd=new O7(this.Lf,this.data,this.anchors,this.ne.$());this.Kd.O();
this.Ib=new z.bA;this.Tu=z.p(this.data.load(),this.qI,this);z.gH(this.Kd.Pn).J("select-anchor",this.rI,this);z.gH(this.Lf).J("show-hidden-note-replies",this.TQ,this).J("start-reply",this.aZ,this).J("save-reply",this.OY,this).J("edit-reply",this.WX,this).J("cancel-reply",this.yX,this).J("delete-reply",this.MX,this).J("approve-note",this.tX,this).J("unapprove-note",this.kZ,this).J("edit-note",this.VX,this).J("save-note",this.NY,this).J("cancel-note",this.xX,this).J("delete-note",this.KX,this).J("hide-note",
this.dY,this);this.Ya.subscribe("historyUpdate",this.uM,this)};var zga=function(a){if(a.me&&a.me.zA())return!0;for(var b in a.Ad)if(a.Ad[b].zA())return!0;return!1};var Aga=function(a){var b=new z.$c,c=a.Wu.open({title:(0,z.H)("Uh oh!"),bodyHtml:(0,z.H)("You have unsaved notes. Are you sure you want to abandon them?"),type:z.b6});c?(c.subscribe(z.kV,b.ib.bind(b,!0)),c.subscribe(z.lV,function(){this.cP();b.cancel()},a)):b.cancel();return b};
var b8=function(a){z.lo(a.me);a.me=null;for(var b in a.Ad)z.lo(a.Ad[b]),delete a.Ad[b]};
var c8=function(a,b,c){var d=b.Sj(),e="PUBLIC"==c?(0,z.H)("Note was made public."):"HIDDEN"==c?(0,z.H)("Note was dismissed."):"NEW"==c?(0,z.H)("Note was made private."):"",g=xga(a.data,b,c);z.r(z.p(g.fe,function(){z.p(this.wG.O(e,{type:z.SW,xw:!0}),function(){g.AR();c8(this,b,d)},this);d8(this,z.Jca,b,{noteState:c,previousNoteState:d})},a),function(a){this.wG.O((0,z.H)("Could not change note state"),z.qT);g.AR();(400>a.status||499<a.status)&&c8(this,b,d)},a);return g.fe};
var e8=function(a,b){var c=b.value;return c?a.Ad[c]:a.me};var Bga=function(a,b){var c=a.ne.og(a.anchors.get(b));return{text:c.W(),image:4==c.type?c.Ud():null}};
var f8=function(a,b){var c=b||a.Ah,d=a.data.Ed(c,a.data.Ta),e=a.Ic.querySelector('[data-note-id\x3d"'+c+'"]');z.u(e,"is-showingNotesReplyCreator");var g=a.Ad["reply_"+c];g||(e=e.querySelector(".notesReply-editor"),g=new X7(a.vB,e,a.ne.$(),c),g.subscribe("change",a.Pk,a),g.subscribe("cancel",function(){g.Qc("")},a),g.subscribe("save",function(a){g.Qc("");m7(d).push(a);d8(this,z.Kca,d,{replyId:a.sd()});w7(this.Wi,d)},a),a.Ad["reply_"+c]=g);g.focus()};
var d8=function(a,b,c,d){d=d||{};d.postId=a.ne.$();d.noteId=c.eb();d.noteType=c.Ki()?"highlight":"paragraph";z.S(b,d)};var g8=function(a,b,c){var d=z.wp(),d=d&&B7(a.anchors,z.uo(d)),e=c&&d&&new Y7(d);z.p(h8(a,b&&b.anchor||a.data.Ta),function(){if(b!=this.Dj){var a=this.Dj;a&&i8(this,a,!1);b&&i8(this,b,!0);this.Dj=b}(a=e&&e.restore())&&a.select()},a)};
var i8=function(a,b,c){var d=b.anchor,e=z7(a.anchors,d);if(e=a.ne.og(e)){z.Zt(e,4);if(c){if(!wga(b,e))return;z.Vt(e,z.qu(b.startIndex,b.endIndex,b.id))}a.anchors.get(d).innerHTML=z.Uw(e,z.x,{mode:a.ne.Rl?"edit":"view",isPublished:!!a.ne.$a().Uk(),media:null,sections:!0,Vi:!1,xi:!1,pf:!1})}};
var j8=function(a,b,c){if(b!=a.Ah){c||z.UU(a.kG,"");(c=a.Ic.querySelector(".is-activeNote"))&&z.v(c,"is-activeNote");c=a.Ah=null;if(b&&a.data.Ta){var d=a.data.Ed(b,a.data.Ta);d&&(c=a.Ic.querySelector('[data-note-id\x3d"'+b+'"]'))&&(z.u(c,"is-activeNote"),a.Ah=b,b=(b=d.Ki())?a.data.Dr(b):null,g8(a,b||null))}z.Cd(a.Ic,"notesItem--selected",!!c)}};
var h8=function(a,b){a.RL=(0,z.Jq)();var c=b!=a.data.Ta;if(c&&zga(a))return z.p(Aga(a),function(){b8(this);return h8(this,b)},a);a.Dj&&(i8(a,a.Dj,!1),a.Dj=null);if(!c)return z.od();j8(a,null);a.data.Ta&&S7(a.Kd,a.data.Ta,!1);b8(a);z.lo(a.Wi);a.Wi=null;z.u(a.Ic,"is-hidingNotesEditor");a.data.Ta=b&&a.Kd.kf[b]?b:"";a.data.Ta?a.Lu():a.MG();a.Pk();return z.od()};
var k8=function(a,b,c,d){(b=z7(a.anchors,b))&&(0,z.Sb)(b.querySelectorAll(".markup--quote"),function(a){var b=a.getAttribute("data-creator-ids").split(" "),b=z.ab(b,c);z.Cd(a,"is-selected",d&&b)},a)};
var l8=function(a,b){if(a.isAuthenticated){z.lo(a.me);var c=a.query(".notesItemEditor"),d=null,e=null;if("string"==typeof b)d=b;else if(b instanceof W7)e=b.highlight,d=e.anchor;else throw Error("Missing assoc for note editor");c.innerHTML="";a.me=new H7(a.vB,c,a.ne.$());nga(a.me,d,Bga(a,d));e&&oga(a.me,e.startIndex,e.endIndex,e.content);a.me.subscribe("change",a.Pk,a);a.me.subscribe("save",a.pI,a);a.me.subscribe("cancel",function(){Q7(this.data,d).rb()?z.u(this.Ic,"is-hidingNotesEditor"):h8(this,
null);j8(this,null)},a);z.v(a.Ic,"is-hidingNotesEditor")}};
var m8=function(a,b,c,d){a8.call(this,a,b,c);this.ho=z.KA(a.get("screen"));this.Za=a.get("dom-monitor");this.Za.subscribe("resize-end",this.hy,this);this.Za.subscribe("inner-resize-end",this.hy,this);this.ae=a.get("element-tracker");z.gH(this.Lf).J("hide-reply",this.eY,this).J("start-note",this.$Y,this).J("show-note-permalink",this.YY,this);d&&(d.subscribe("highlight",this.tM,this),this.Sc=d);[this.anchors.Iq].forEach(function(a){this.Gc.push(z.Oy(a,"click",this.SY,this))},this);this.$x=new z.VS;
this.$x.O();z.ko(this,z.ua(z.lo,this.$x));iga(this.$x,this.LW.bind(this));this.$x.subscribe("dismiss",this.PX,this)};var n8=function(a){if(a.me){var b=a.ho,c=b.scrollTop,d=b.scrollLeft;a.me.focus();b.scrollTop=c;b.scrollLeft=d}};var o8=function(a,b){for(var c=b?1:-1,d=a.parentNode.childNodes,e=d.length,g=(0,z.bb)(d,a),h=z.uD(a,0),k=z.Wq(h),h=1!=z.Bl(h),m=a,g=g+c;0<=g&&g<e;g+=c){var q=d[g];if("SECTION"===q.tagName){var t=z.uD(q,0),A=z.Wq(t),t=1!=z.Bl(t);if(k!=A||t||h)break;else m=q}}return m};
var p8=function(a){var b=a.Dz.querySelectorAll(".js-is-spacedForNoteList"),c=!1;(0,z.xb)(b,function(a){a.style.paddingBottom="";a.style.paddingTop="";z.v(a,"js-is-spacedForNoteList");c=!0});c&&(T7(a.Kd),a.ae.Ui())};var q8=function(a,b){g8(a,b.highlight);r8(a,{scroll:!0,dk:!0});l8(a,b);a.me&&n8(a);a.U("show")};var Cga=function(a){return!!z.az(a,function(a){a=z.cD(a);return 3==a||7==a})};var s8=function(a,b){Q7(a.data,b).rb()||(l8(a,b),a.me&&n8(a))};
var t8=function(a,b){z.p(h8(a,b),function(){s8(this,b);p8(this);u8(this,{scroll:!0,dk:!0});this.Ic.style.top=Math.round(z.fz(this.Kd.kf[b]))+"px";this.Pk()},a)};var Dga=function(a,b,c){if(!a.data.Ta)return z.od(!0);p8(a);var d=z.fz(b);c&&(d-=z.ez(c,a.Ic).y);d=Math.round(d+z.mq(b).top);a.Ic.style.top=d+"px";a.Pk();if(1>Math.abs(a.Ic.offsetTop-d)||!(0,z.T5)())return z.od(!0);b=new z.$c;z.Ny(a.Ic,z.K3,b.ib.bind(b,a));return b};
var v8=function(a,b,c){var d=a.anchors.get(a.data.Ta);if(!a.isAuthenticated){var e=a.data.Ta,e=a.Dj?e+("--highlight-"+a.Dj.startIndex+"-"+a.Dj.endIndex):e+"--newNote";a.Ic.querySelector(".button--addNotes").setAttribute("data-redirect",z.AR.uH()+"#"+e)}d&&(e=d.querySelector(".markup--highlight"),d=c.dk&&e?e:d,(e=z.az(b,function(a){return z.ud(a,"js-notesList")}))&&(b=e),a=Dga(a,d,b),c.scroll&&z.p(a,function(){z.nz(b,z.ifa)}))};
var r8=function(a,b){var c=a.Ic.querySelector(".newNoteEditor");c&&v8(a,c,b)};var w8=function(a,b,c){b=a.Ic.querySelector('[data-note-id\x3d"'+b+'"]');v8(a,b,c)};var u8=function(a,b){if(a.data.Ta){var c=Q7(a.data,a.data.Ta),d=c.rb();(c=d?c.Qo(0).eb():null)?(1==d&&j8(a,c),b.dk=!1,w8(a,c,b)):r8(a,b)}};var x8=function(a,b){return b==a.data.Ta?z.p(h8(a,null),z.vG):z.p(h8(a,b),z.ec(!!b))};
var y8=function(a,b,c){var d=z.Hf(b.target,"notesItem");!d||b.relatedTarget&&z.tf(d,b.relatedTarget)||!(b=a.data.Ed(d.getAttribute("data-note-id"),a.data.Ta))||(d=null,c?d=b.Ki():a.Ah&&(d=a.data.Ed(a.Ah,a.data.Ta).Ki()),g8(a,d?a.data.Dr(d):null,a.ne.Rl))};var z8=function(a){z.ho.call(this);this.ca=a};var A8=function(a,b){z.CA.call(this);this.ca=a;this.$b=b;this.bt()};var B8=function(a){a=z.Up(a.$b,"transform").match(/translate3d\(([^,]*)/);return(0,window.parseInt)(a?a[1]:0,10)};
var C8=function(a,b,c,d){var e=b!=a.Wy;a.Wy=b;a.by=b*a.Xy;z.Rp(a.$b,"transition-duration",c);z.Rp(a.$b,"transform","translate3d("+a.by+"px,0,0)");if(e||d){c=b=Math.abs(b);d=a.$b.children;if(10<d.length){if(e=a.$b.parentNode.getElementsByClassName("slideIndicator-fraction")[0])e.innerHTML=c+1+" of "+d.length}else if(d=a.$b.parentNode.getElementsByClassName("slideIndicators")[0])(e=d.getElementsByClassName("is-active")[0])&&z.v(e,"is-active"),(e=d.children[c])&&z.u(e,"is-active");a.U("slide",b,a)}};
var D8=function(a,b,c){a8.call(this,a,b,c);this.mM=this.query(".notesItems");this.bD=a.get("diagnostics");this.$b=new A8(a,this.mM);this.$b.subscribe("slide",this.xM,this);this.Ag=this.Vy=null;z.gH(this.Lf).J("dismiss-note",this.rE,this).J("toggle-note-dropdown",function(a){z.Dd(a.target,"is-open")});this.Gc.push(z.Oy(this.Lf,"click",this.sM,this));this.Gc.push(z.Oy(this.Dz,"click",this.sM,this));this.Gc.push(z.Oy(this.Lf,"focusout",this.aY,this))};
var E8=function(a,b){if(a.Dj){var c=a.Dz.querySelector(".markup--highlight"),d=a.Ic.querySelector(".is-activeNote");if(d&&c){var d=window.innerHeight-d.offsetHeight+20,e=c.offsetHeight,c=z.fz(c);e<d&&(c-=(d-e)/2);a.Ag&&a.Ag.cancel();b?a.Ag=new z.vW(a.ln,"scrollTop",200,Math.max(c,0)):z.dz(a.ln,0,c)}}};var F8=function(a,b){a.$b.enable();z.p(h8(a,b),function(){var a=Q7(this.data,this.data.Ta).rb();this.Vy=z.Hy(tga,{count:a});this.Ic.appendChild(this.Vy);C8(this.$b,0,"0",!0)},a)};
var G8=function(a){z.ho.call(this);this.ca=a};var H8=function(a,b){z.ho.call(this);this.Ba=a.get("modelRequest");this.ga=a.get("modelStore");this.Ky=a.get("request");this.L=a.get("routeBuilder");this.Ga=b;this.zd=null;this.Nq={};this.pj=new z.k1;this.pj.subscribe("add",this.ON,this);this.pj.subscribe("remove",this.ON,this);z.ko(this,z.ua(z.lo,this.pj))};var Ega=function(a,b,c,d){return(0,z.wd)(a.Nq[b.name]||[],function(a){return a.Vb()==c&&a.zc()==d})};var R7=function(a,b){return I8(a,a.Nq[b]||[])};
var Fga=function(a,b,c,d){b=Ega(a,b,c,d);return I8(a,b)};var J8=function(a,b,c,d,e){return z.p(a.create(b,c,d,0,e),function(a){this.pj.add(a);return a},a)};var K8=function(a,b,c,d){return(a=L8(a,b,c,d))&&a.ua()==z.Fj().userId?a:null};var L8=function(a,b,c,d){a=a.Nq[b.name]||[];if(!a.length)return null;b=null;for(var e=0;e<a.length;e++){var g=a[e];if(!(c<g.Vb()||d>g.zc())&&(b&&"anon"!=b.ua()||(b=g),g.ua()==z.Fj().userId))return g}return b};
var Gga=function(a){var b=a.ob()[0].name;a=a.$a().Va().bodyModel.paragraphs;return z.Xa(a,function(a){return a.name==b})};var M8=function(a,b){return q7(b,function(a){return a.ob()[0].getName()},a)};var I8=function(a,b){b=b.filter(function(a){return"anon"!=a.ua()});var c=q7(b,function(a){return a.ua()},a);return z.Db(c).map(function(a){return new Hga(a[0].Fc(),a)},a)};var Hga=function(a,b){this.user=a;this.quotes=b};
var N8=function(a,b,c){z.EA.call(this);this.fc=new H8(a,b.$());z.ko(this,z.ua(z.lo,this.fc));var d=this.fc.pj;d.subscribe("add",this.YM,this);d.subscribe("remove",this.YM,this);this.tb=b;this.qc=b.Yh;this.li=c;this.li.nw(this.fc);this.PK=[];this.wa=a.get("app");this.oa=a.get("popover");this.L=a.get("routeBuilder");this.vD=a.get("global-event-bus")};
var O8=function(a,b,c,d){var e=P8(a,b);e&&(c=z.r3(z.sR(z.uR(z.s3(z.tR(z.vR(a.oa),pga,e),"top"),c),"popover--dark popover--quoteAttributions"),d).O())&&(c.De("deactivate",function(){this.Kk===b&&Q8(this,null)},a),c.Xk().J("quote",a.cW.bind(a,c)).J("quote-respond",a.dW.bind(a,c)))};
var P8=function(a,b){if("anon"==b.ua())return{La:!1,k3:!0};var c=R8(a,b),d=b.Vb(),e=b.zc(),c=Fga(a.fc,c,d,e);if(!c||!c.length)return null;c=(0,z.Sb)(c,function(a){return a.user});d=(0,z.wd)(c,function(a){return a.userId!=z.Fj().userId});return{La:(0,z.kd)(c,function(a){return a.userId==z.Fj().userId}),social:d,Ce:c.length}};var Iga=function(a,b){var c=a.qc.querySelectorAll('.markup--quote[name~\x3d"'+b.Xe()+'"]');return z.hb(c)};
var R8=function(a,b){var c=b.ob()[0].name;return(c=z.sz(a.qc,c))?a.tb.og(c):null};var S8=function(a,b){var c=z.yp(b);return(c=z.eX(a.li,c))?L8(a.fc,c.Or,c.start,c.end):null};var Q8=function(a,b){a.Kk!==b&&(a.Kk&&T8(a,a.Kk,!1),b&&T8(a,b,!0),a.Kk=b)};var T8=function(a,b,c){Iga(a,b).map(function(a){z.Cd(a,"is-targeted",c)})};var U8=function(a,b){var c=b.ob(),d=z.sz(a.qc,c[0].getName()),c=z.sz(a.qc,z.Va(c).getName());(d=z.sG(d,b.Vb(),c,b.zc()))&&z.kH(a.ng(),d)};
var V8=function(a,b,c,d){z.S(c?z.u5:z.Oca,{postId:a.tb.$(),quoteId:b,source:d})};var W8=function(a){this.ca=a};z.rW.prototype.zA=z.X(175,function(){return this.In.trim()!=this.Va().trim()});z.CJ.prototype.ZI=z.X(173,function(a){a!=this.Cx&&this.Ka&&(this.Ka.Be.contentEditable=a);this.Cx=a});z.Zj.prototype.lw=z.X(146,function(a){return z.C(this,"highlight",a)});z.Zj.prototype.Dr=z.X(145,function(){return z.B(this,"highlight")});z.Zj.prototype.gw=z.X(144,function(a){return z.C(this,"author",a)});
z.bk.prototype.gw=z.X(143,function(a){return z.C(this,"author",a)});z.lj.prototype.Qj=z.X(142,function(){return z.B(this,"quotes")});z.Sj.prototype.Qj=z.X(141,function(){return z.B(this,"quotes")});z.um.prototype.Qj=z.X(140,function(){return z.B(this,"quotes")});z.Am.prototype.Qj=z.X(139,function(){return z.B(this,"quotes")});z.J1.prototype.Qj=z.X(138,function(a){return z.p(this.R.get(z.w(this.L,z.Y4,{postId:a}),{background:!0,json:!0}),this.Cc.bind(this,z.vm))});
z.hh.prototype.Ki=z.X(85,function(){return z.B(this,"highlightId")});z.Zj.prototype.Ki=z.X(84,function(){return z.B(this,"highlightId")});z.ek.prototype.Ki=z.X(83,function(){return z.B(this,"highlightId")});z.hh.prototype.Zg=z.X(82,function(a){return z.C(this,"authorId",a)});z.ih.prototype.Zg=z.X(81,function(a){return z.C(this,"authorId",a)});z.zh.prototype.Zg=z.X(80,function(a){return z.C(this,"authorId",a)});z.Zj.prototype.Zg=z.X(79,function(a){return z.C(this,"authorId",a)});
z.bk.prototype.Zg=z.X(78,function(a){return z.C(this,"authorId",a)});z.Ym.prototype.Zg=z.X(77,function(a){return z.C(this,"authorId",a)});z.hh.prototype.Ih=z.X(76,function(){return z.B(this,"authorId")});z.ih.prototype.Ih=z.X(75,function(){return z.B(this,"authorId")});z.zh.prototype.Ih=z.X(74,function(){return z.B(this,"authorId")});z.Zj.prototype.Ih=z.X(73,function(){return z.B(this,"authorId")});z.bk.prototype.Ih=z.X(72,function(){return z.B(this,"authorId")});
z.Ym.prototype.Ih=z.X(71,function(){return z.B(this,"authorId")});z.Ng.prototype.Uf=z.X(49,function(a){return z.C(this,"state",a)});z.hh.prototype.Uf=z.X(48,function(a){return z.C(this,"state",a)});z.ih.prototype.Uf=z.X(47,function(a){return z.C(this,"state",a)});z.rj.prototype.Uf=z.X(46,function(a){return z.C(this,"state",a)});z.sj.prototype.Uf=z.X(45,function(a){return z.C(this,"state",a)});z.Zj.prototype.Uf=z.X(44,function(a){return z.C(this,"state",a)});
z.bk.prototype.Uf=z.X(43,function(a){return z.C(this,"state",a)});z.Gg.prototype.sd=z.X(35,function(){return z.B(this,"replyId")});z.Hg.prototype.sd=z.X(34,function(){return z.B(this,"replyId")});z.dh.prototype.sd=z.X(33,function(){return z.B(this,"replyId")});z.ih.prototype.sd=z.X(32,function(){return z.B(this,"replyId")});z.jj.prototype.sd=z.X(31,function(){return z.B(this,"replyId")});z.lj.prototype.sd=z.X(30,function(){return z.B(this,"replyId")});
z.Mj.prototype.sd=z.X(29,function(){return z.B(this,"replyId")});z.bk.prototype.sd=z.X(28,function(){return z.B(this,"replyId")});z.fk.prototype.sd=z.X(27,function(){return z.B(this,"replyId")});z.Tk.prototype.sd=z.X(26,function(){return z.B(this,"replyId")});z.Gg.prototype.eb=z.X(25,function(){return z.B(this,"noteId")});z.Hg.prototype.eb=z.X(24,function(){return z.B(this,"noteId")});z.Kg.prototype.eb=z.X(23,function(){return z.B(this,"noteId")});
z.dh.prototype.eb=z.X(22,function(){return z.B(this,"noteId")});z.hh.prototype.eb=z.X(21,function(){return z.B(this,"noteId")});z.ih.prototype.eb=z.X(20,function(){return z.B(this,"noteId")});z.jh.prototype.eb=z.X(19,function(){return z.B(this,"noteId")});z.jj.prototype.eb=z.X(18,function(){return z.B(this,"noteId")});z.lj.prototype.eb=z.X(17,function(){return z.B(this,"noteId")});z.Mj.prototype.eb=z.X(16,function(){return z.B(this,"noteId")});z.Zj.prototype.eb=z.X(15,function(){return z.B(this,"noteId")});
z.bk.prototype.eb=z.X(14,function(){return z.B(this,"noteId")});z.ek.prototype.eb=z.X(13,function(){return z.B(this,"noteId")});z.fk.prototype.eb=z.X(12,function(){return z.B(this,"noteId")});z.Qk.prototype.eb=z.X(11,function(){return z.B(this,"noteId")});z.Tk.prototype.eb=z.X(10,function(){return z.B(this,"noteId")});var o7=/^[@＠][a-z0-9_]{1,15}$/i;z.n(r7,z.EA);z.f=r7.prototype;z.f.ZL=function(a){return a.Hb()};z.f.Ku=null;z.f.XC=null;z.f.fa=function(){return this.Ja};
z.f.V=function(){r7.H.V.call(this);z.FA(this,this.gi,"change",this.HX,this);z.FA(this,this.gi,"add",this.nY,this);z.FA(this,this.gi,"remove",this.oY,this);t7(this,!0)};z.f.ka=function(){this.Ja.innerHTML="";delete this.Ja;r7.H.ka.call(this)};z.f.getData=function(){return this.gi};z.f.nY=function(a,b){if(this.La())for(var c=0;c<a.length;c++){var d=b.indexOf(a[c]),d=u7(this,a[c],d);this.U("after-draw",a[c],d)}};
z.f.oY=function(a){if(this.La()){var b=this.Ja.querySelector("#"+x7(this,a));this.U("before-clear",a,b);this.U("destroy",a,b);z.kf(b)}};z.f.HX=function(a){for(var b=0;b<a.length;b++)w7(this,a[b])};y7.prototype.get=function(a){return z7(this,a)};z.n(E7,z.lY);E7.prototype.ts="left";E7.prototype.Es=function(){var a=z.w(this.pB,z.c5,{},{source:"typeahead",q:this.query.substring(1)});return this.request.get(a,{json:!0})};z.n(F7,z.CJ);z.f=F7.prototype;z.f.jF=!1;z.f.In="";z.f.uu=0;z.f.mp=z.h4;z.f.zA=function(){return this.In.trim()!=this.Va().trim()};z.f.eb=function(){return this.nX};z.f.save=function(){this.Va().length<=this.mh&&this.eo()};z.f.PG=function(){this.oO()&&(0,window.confirm)(this.iP())?(z.r(this.si.ge(this.vH()),z.yM(this.X,(0,z.H)("Sorry, your attempt to delete failed. Please try again."))),this.U("delete")):G7(this)};z.f.Ma=function(){(0,window.clearTimeout)(this.uu);F7.H.Ma.call(this)};
z.f.V=function(){function a(a){a.stopPropagation()}F7.H.V.call(this);this.In=this.Va();this.Qc(this.In);this.gr(13,this.tE,this);this.gr(27,this.uE,this);this.Ka.listen("blur",this.sE,!1,this);var b=this.Ka.fa();z.Oy(b,"keydown",a);z.Oy(b,"keyup",a);z.Oy(b,"keypress",a)};z.f.xs=function(a){return a};
z.f.eo=function(){if(this.isEnabled()){var a=this.Va().trim();if(a){this.ZI(!1);var b=this.vH(),c=this.sP(),a=this.tP(a);z.gd(z.r(z.p(this.si.send(c,b,a,{json:!0}),this.wY,this),z.yM(this.X,(0,z.H)("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again."))),this.ZI.bind(this,!0))}else z.Kq(this.PG,this)}};z.f.wY=function(a){a=z.CW(a.value,a.references);this.U("save",this.xs(a))};
z.f.tE=function(a){if(this.vm&&this.vm.sh)return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};z.f.uE=function(a){if(this.vm&&this.vm.sh)return!1;a.preventDefault();G7(this);return!1};z.f.sE=function(){this.jF&&(this.Va().length>=this.mh?(0,window.confirm)(this.vP())?G7(this):this.focus():this.uu=(0,window.setTimeout)(this.eo.bind(this),100))};z.n(H7,F7);z.f=H7.prototype;z.f.AC=null;z.f.pK=null;z.f.BC=null;z.f.PD=null;z.f.OD=null;z.f.xL=null;z.f.iP=function(){return(0,z.H)("Are you sure you want to delete this note?")};z.f.vP=function(){return(0,z.H)("Your note is too long; do you want to abandon your changes?")};z.f.oO=function(){return!!this.eb()};
z.f.xs=function(a){var b=z.Ey();return(new z.Zj({postId:a.postId,anchor:a.anchor,noteId:a.noteId,content:a.content,state:a.state,createdAt:a.createdAt,replies:[],highlight:a.highlight||null,highlightId:a.highlightId||null})).gw(b).Zg(b.ua())};z.f.sP=function(){return this.eb()?"put":"post"};z.f.vH=function(){return this.eb()?z.w(this.L,z.hba,{postId:this.Ga,noteId:this.eb()}):z.w(this.L,z.fba,{postId:this.Ga})};
z.f.tP=function(a){a={content:a};this.AC&&(a.anchor=this.AC,a.anchorContent=this.pK,a.anchorImage=this.BC?this.BC.Hb():null);null!=this.PD&&null!=this.OD&&(a.highlightStart=this.PD,a.highlightEnd=this.OD,a.highlightContent=this.xL);return a};z.n(O7,z.EA);z.f=O7.prototype;z.f.nw=function(a){this.fc=a;Object.keys(a.Nq).map(this.zw,this);a=a.pj;a.subscribe("add",this.PN,this);a.subscribe("remove",this.PN,this)};z.f.PN=function(a){Object.keys(M8(this.fc,a instanceof Array?a:[a])).map(this.zw,this)};z.f.zw=function(a){if(this.hb.Pi()){var b=a||this.hb.Ta;if(a=this.kf[b]){var b=P7(this,b),c=z.x.Oa();c.enable_quotes&&c.combined_margin_quotes?(z.Gy(a,L7,b),z.Cd(a,"is-withNotes",0<b.Yj||0<b.zs)):(z.Gy(a,L7,b),z.Cd(a,"is-withNotes",0<b.Yj))}}};
z.f.rX=function(a){if(a=C7(this.zg,a.target)){var b=z7(this.zg,a),c=this.kf[a];!c||c===this.yq||!b||z.Zy(b,!1)||z.ud(b,"graf--layoutInsetLeft")||z.ud(b,"graf--layoutOutsetLeft")||(this.yq&&z.v(this.yq,"is-highlighted"),z.u(c,"is-highlighted"),this.yq=c,z.lo(this.cq),this.cq=new z.rY(b),this.cq.kc(c),this.cq.O(),this.cq.De("dismiss",function(){z.v(c,"is-highlighted");this.yq===c&&(this.yq=null)},this))}};
z.f.V=function(){O7.H.V.call(this);z.Iy()||[this.zg.Iq].forEach(function(a){this.listen(a,"mouseover",this.rX)},this)};z.f.Ma=function(){z.lo(this.cq);z.kf(this.Pn);this.kf=this.Pn=null;O7.H.Ma.call(this)};z.n(U7,z.CA);z.f=U7.prototype;z.f.load=function(){this.Bg||(this.Bg=z.r(z.p(this.si.get(z.w(this.L,z.gba,{postId:this.Ga}),{json:!0,background:!0}),this.RZ,this),z.T));return this.Bg.Db()};z.f.Pi=function(){return this.NK};z.f.nA=function(){return this.GM};z.f.og=function(a){var b=a&&a.getAttribute("name");if(!b||!a)return null;var c=this.au[b];return c&&!this.Rl?c:this.au[b]=z.zD(a)};z.f.Dr=function(a){return this.yL[a]||null};z.f.Ed=function(a,b){return Q7(this,b).sr(a)};
z.f.sH=function(){return Q7(this,"vote")};z.f.lw=function(a,b){this.yL[a]=b};z.f.$=function(){return this.Ga};
z.f.RZ=function(a){var b=a.references.User;this.gm=b[a.post.creatorId];this.GM=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,h=b;if(g)for(var k=0;k<g.length;k++){var m=g[k],q=m.authorId||null;m.author=q&&h[q]||null}g=e.anchor;h=e.authorId||null;e.author=h&&b[h]||null;g=Q7(this,g);e=z.ak(e);g.add(z.pC(this.ga,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.lw(a[b].id,z.wi.lb(z.dk,a[b]));this.NK=!0};
z.f.ha=function(){this.Bg.cancel();U7.H.ha.call(this)};z.n(X7,F7);z.f=X7.prototype;z.f.iP=function(){return(0,z.H)("Are you sure you want to delete this reply?")};z.f.vP=function(){return(0,z.H)("Your reply is too long; do you want to abandon your changes?")};z.f.oO=function(){return!!this.Iy};z.f.xs=function(a){var b=z.Ey();return(new z.bk({postId:a.postId,noteId:a.noteId,replyId:a.replyId,content:a.content,createdAt:a.createdAt})).gw(b).Zg(b.ua())};z.f.sP=function(){return this.Iy?"put":"post"};
z.f.vH=function(){return this.Iy?z.w(this.L,z.kba,{postId:this.Ga,noteId:this.eb(),replyId:this.Iy}):z.w(this.L,z.jba,{postId:this.Ga,noteId:this.eb()})};z.f.tP=function(a){return{content:a}};z.n(Y7,z.no);Y7.prototype.cw=function(){if(!this.Gg)return null;var a=$7(this.Gg);if(!a)return null;var b=$7(this.hj);return b?z.Yo(a.node,a.offset,b.node,b.offset):null};z.n(a8,z.CA);z.f=a8.prototype;z.f.me=null;z.f.Ah=null;z.f.Dj=null;z.f.Wi=null;z.f.cn=0;z.f.ha=function(){b8(this);h8(this,null);var a;(a=this.ne.$a().pi)&&a.unsubscribe(z.dZ,this.nL,this);this.Ya.unsubscribe("historyUpdate",this.uM,this);this.jM&&z.Py(this.jM);z.Py(this.Gc);this.Gc.length=0;z.VJ(this.Kd.Pn);z.VJ(this.Lf);z.kf(this.Lf);this.data.Uc();this.Tu&&this.Tu.cancel();z.lo(this.Kd);z.lo(this.Ib);this.jM=this.fc=this.Tu=this.data=this.Lf=this.anchors=this.Kd=null;a8.H.ha.call(this)};
z.f.nw=function(a){this.fc=a;this.Kd.nw(a)};z.f.nL=function(){var a=this.ne.$a();z.x.Oa().enable_recommend_notes&&this.uN.$o()!=a.$o()&&(this.uN=a.clone(),!a.$o()&&(a=vga(this.data)))&&(d8(this,z.t5,a),this.data.sH().remove(a))};z.f.qI=function(){};z.f.aB=function(){};z.f.pI=function(a){a.Dr()&&(this.data.lw(a.Ki(),a.Dr()),a.lw(null));V7(this.data,a);d8(this,z.Hca,a)};z.f.rI=function(){};z.f.SQ=function(){};z.f.Pk=function(){};z.f.cP=function(){};z.f.rV=function(a){return a.Hb()};
z.f.aZ=function(a){f8(this,a.value)};z.f.OY=function(a){(a=this.Ad["reply_"+a.value])&&a.save()};z.f.yX=function(a){var b=this.Ad["reply_"+a.value];b&&G7(b);(a=z.Hf(a.target,"notesItem"))&&z.v(a,"is-showingNotesReplyCreator")};
z.f.WX=function(a){function b(){var a=this.data.Ed(d,this.data.Ta);w7(this.Wi,a);z.v(g,"is-notesEditMode");z.lo(h);delete this.Ad["reply_"+e]}var c=a.value.split(","),d=c[0],e=c[1],c=z.Hf(a.target,"notesItem"),g=z.Hf(a.target,"notesReply");z.u(g,"is-notesEditMode");z.v(c,"is-showingNotesReplyCreator");a=g.querySelector(".notesContent");var h=new X7(this.vB,a,this.ne.$(),d,e);h.subscribe("save",function(a){for(var c=this.data.Ed(d,this.data.Ta),g=m7(c),h=0;h<g.length;h++)if(g[h].sd()==e){g[h]=a;break}d8(this,
z.Lca,c,{replyId:e});b.call(this)},this);h.subscribe("delete",function(){for(var a=this.data.Ed(d,this.data.Ta),c=m7(a),g=0;g<c.length;g++)if(c[g].sd()==e){z.eb(c,g);break}d8(this,z.Mca,a,{replyId:e});b.call(this)},this);h.subscribe("cancel",function(){b.call(this)},this);h.subscribe("change",this.Pk,this);h.focus(1);this.Ad["reply_"+e]=h};z.f.MX=function(a){(a=this.Ad["reply_"+a.value])&&a.PG()};
z.f.uX=function(a){a=a.eb();this.Ad[a]&&(z.lo(this.Ad[a]),delete this.Ad[a]);this.Ad["reply_"+a]&&(z.lo(this.Ad["reply_"+a]),delete this.Ad["reply_"+a])};z.f.qX=function(a,b){z.v(b,"is-showingNotesReplyCreator");b.setAttribute("data-note-id",a.eb())};z.f.tX=function(a){z.r(c8(this,this.data.Ed(a.value,this.data.Ta),"PUBLIC"),z.yM(this.Wu,(0,z.H)("Sorry, we couldn’t approve the note. Please try again later and make sure you are logged in.")))};
z.f.kZ=function(a){z.r(c8(this,this.data.Ed(a.value,this.data.Ta),"NEW"),z.yM(this.Wu,(0,z.H)("Sorry, we couldn’t unapprove the note. Please try again later and make sure you are logged in.")))};
z.f.VX=function(a){function b(){z.v(d,"is-notesEditMode");z.lo(g);delete this.Ad[c]}var c=a.value,d=z.Hf(a.target,"notesItem");z.u(d,"is-notesEditMode");z.v(d,"is-showingNotesReplyCreator");var e=d.querySelector(".notesContent"),g=new H7(this.vB,e,this.ne.$(),a.value);g.subscribe("save",function(a){V7(this.data,a);d8(this,z.Ica,a);b.call(this)},this);g.subscribe("delete",function(){var a=Q7(this.data,this.data.Ta),d=a.sr(c);d8(this,z.t5,d);a.remove(d);b.call(this)},this);g.subscribe("cancel",function(){var a=
this.data.Ed(c,this.data.Ta);w7(this.Wi,a);b.call(this)},this);g.subscribe("change",this.Pk,this);g.focus(1);this.Ad[c]=g};z.f.NY=function(a){(a=e8(this,a))&&a.save()};z.f.xX=function(a){(a=e8(this,a))&&G7(a)};z.f.KX=function(a){(a=e8(this,a))&&a.PG()};z.f.vY=function(a){for(var b=0;b<a.length;b++)this.Kd.zw(a[b].tc())};z.f.dY=function(a){var b=a.value,c=this.data.Ed(b,this.data.Ta);z.r(z.p(c8(this,c,"HIDDEN"),function(){this.aB(c);this.Ah==b&&(this.Ah=null)},this),z.yM(this.Wu,(0,z.H)("Sorry, we couldn’t hide the note. Please try again later and make sure you are logged in.")))};
z.f.uY=function(a){a.subscribe("add",this.vY,this);a.subscribe("change",this.SQ,this);a.subscribe("remove",this.aB,this)};z.f.query=function(a){return this.Lf.querySelector(a)};z.f.Rp=function(){T7(this.Kd);this.Kd.kf[this.data.Ta]||h8(this,null)};z.f.TQ=function(a){this.kJ(a)};z.f.kJ=function(a){(a=z.Hf(a.target,"notesReplies"))&&z.v(a,"notesReplies--hidden")};
z.f.Lu=function(){var a=this.data.Ta,b=this.query(".notesItems"),c=Q7(this.data,a),d=z.x.Oa();if(d.enable_quotes&&d.combined_margin_quotes){var a=this.fc?R7(this.fc,a):[],d=this.query(".js-quotesList"),e=z.Hy(J7,{II:a});z.lf(e,d);z.Iy()||z.Oy(e,"mouseover",this.hW,this);a.length||z.zz(e)}b=new r7(b,c,sga);b.ML="notesItem";b.ZL=this.rV.bind(void 0);t7(b);this.Wi=s7(b,{Em:this.Em,DI:this.data.gm,cn:this.cn});this.Wi.subscribe("before-clear",this.uX,this);this.Wi.subscribe("after-draw",this.qX,this);
this.Wi.O();S7(this.Kd,this.data.Ta,!0);z.u(this.screen.aa(),"is-notesListVisible");z.Xz(z.Gca)};z.f.hW=function(a){if((a=z.az(a.target,function(a){return!!a.getAttribute("data-quote-ids")},a.currentTarget))&&this.hK!=a){this.xn&&this.xn.NO();var b=this.data.Ta,c=a.getAttribute("data-quote-creator-id");this.hK=a;this.xn=new z.rY(z7(this.anchors,b),300);this.xn.kc(a);this.xn.subscribe("dismiss",function(){k8(this,b,c,!1);z.lo(this.xn);this.xn=this.hK=null},this);this.xn.O();k8(this,b,c,!0)}};
z.f.MG=function(){z.UU(this.kG,"");z.v(this.screen.aa(),"is-notesListVisible")};z.f.getSelection=function(a){var b=z.wp();if(!b||b.isCollapsed())if(a&&(b=a),!b||b.isCollapsed())return null;a=z.uo(b);var c=B7(this.anchors,a);if(!c)return null;c=(a=z.az(a,z.VC,c))&&this.ne.og(a);if(!a)return null;var d=z.tz(b,a,!0),e=z.tz(b,a,!1);return-1==d||-1==e?null:new W7(b,a,new z.dk({anchor:a.getAttribute("name"),startIndex:d,endIndex:e,content:c.W().substring(d,e)}))};z.f.uM=function(){this.Cz(z.FX())};z.n(m8,a8);z.f=m8.prototype;z.f.cn=3;z.f.Ql=!1;z.f.Sc=null;
z.f.qI=function(){var a=(0,z.Jq)();this.Tu=null;this.Ql=!0;var b=z.FX();this.Rp();if(this.isAuthenticated){var c=this.data.gm.userId===z.Fj().userId;z.Cd(this.Ic,"is-notesCreator",c)}z.h6(this.query(".js-notesPostCreator"),this.data.gm.name);this.Cz(b);this.Gc.push(z.Oy(this.Lf,"mouseover",this.FX,this));this.Gc.push(z.Oy(this.Lf,"mouseout",this.EX,this));this.Gc.push(z.Oy(this.Ic,"click",this.zX,this));this.Gc.push(z.Oy(this.Dz,z.K3,this.AE,this));z.Yz("notes.renderMarkers",(0,z.Jq)()-a)};
z.f.Cz=function(a){if(a.Qf&&this.Kd.kf[a.Qf])if("highlight"==a.Ok){t8(this,a.Qf);var b=this.anchors.get(a.Qf),c=a.startIndex,d=a.endIndex;if(z.ka(c)&&z.ka(d)){var e=z.sG(b,c,b,d);e&&(b=new W7(e,b,new z.dk({anchor:a.Qf,startIndex:c,endIndex:d,content:e.W()})),q8(this,b))}}else a.noteId?(z.p(h8(this,a.Qf),function(){s8(this,a.Qf)},this),j8(this,a.noteId,!0),w8(this,a.noteId,{scroll:!0,dk:!0}),"reply"==a.Ok&&f8(this)):"newNote"==a.Ok&&t8(this,a.Qf)};
z.f.pI=function(a){m8.H.pI.call(this,a);this.me.Qc("");j8(this,a.eb());z.u(this.Ic,"is-hidingNotesEditor")};z.f.cP=function(){var a={scroll:!0,dk:!0};if(this.me)r8(this,a),n8(this);else{var b;a:{b=this.Ad;for(var c in b){b=b[c];break a}b=void 0}if(c=b&&b.eb())j8(this,c),w8(this,c,a),b.focus()}};z.f.Lu=function(){m8.H.Lu.call(this);D7(this.anchors,this.Lf,this.anchors.get(this.data.Ta))};
z.f.Pk=function(){var a=this.ho.scrollTop;p8(this);var b=(0,window.parseInt)(this.Ic.style.top,10);if(!(0,window.isNaN)(b)){var c=this.data.Ta;if(c=c?this.anchors.get(c):null)if(c=z.UC(c,B7(this.anchors,c))){var d=o8(c,!1),c=o8(c,!0),e=!1,g=z.fz(d);b<g&&(e=g-b,d.style.paddingTop=z.mq(d).top+e+"px",this.Ic.style.top=b+e+"px",z.u(d,"js-is-spacedForNoteList"),e=!0);b+=this.Ic.offsetHeight;d=z.fz(c)+c.offsetHeight;b>d&&(b-=d,c.style.paddingBottom=z.mq(c).bottom+b+"px",z.u(c,"js-is-spacedForNoteList"),
e=!0);this.ho.scrollTop=a;e&&(T7(this.Kd),this.ae.Ui())}}};z.f.rI=function(a){z.p(x8(this,a.value),function(a){a&&(this.data.Ta&&Q7(this.data,this.data.Ta).rb()||((a=this.getSelection())&&a.highlight.anchor==this.data.Ta?(g8(this,a.highlight),l8(this,a)):l8(this,this.data.Ta),this.me&&n8(this),this.U("show")),u8(this,{scroll:!0,dk:!0}))},this)};z.f.aB=function(a){this.Kd.zw(a.tc());a.eb()==this.Ah&&g8(this,null)};z.f.kJ=function(a){z.v(z.Hf(a.target,"notesReplies"),"notesReplies--hidden");this.Pk()};
z.f.SY=function(a){if(!this.ne.Rl&&!Cga(a.target)&&(z.Iy()||this.data.Ta)){var b=this.getSelection();if(!b||b.Do!=this.data.Ta){if(this.data.Ta&&z.Iy())return h8(this,null);500>(0,z.Jq)()-this.RL||(a=C7(this.anchors,a.target),z.p(x8(this,a),function(a){var b=this.data.Ta;a&&b&&(s8(this,b),u8(this,{scroll:!0,dk:!0}))},this))}}};z.f.hy=function(){this.Rp()};
z.f.LW=function(a){if(!this.data.Ta)return!1;a=a.target;return z.wz(a)?!0:!!z.az(a,function(a){return a==this.Ic||a==this.Kd.Pn||this.Sc&&a==this.Sc.fa()||a.getAttribute("data-action")&&"zoom"!=a.getAttribute("data-action")}.bind(this))};z.f.PX=function(){this.data.Ta&&h8(this,null)};z.f.YY=function(a){z.UU(this.kG,a.value)};z.f.FX=function(a){y8(this,a,!0)};z.f.EX=function(a){y8(this,a,!1)};z.f.tM=function(){if(!this.Sc)return!1;var a=this.getSelection(this.Sc.qo);z.hH(this.Sc);a&&q8(this,a);return!1};
z.f.eY=function(a){a=a.value.split(",");var b=a[0],c=a[1];z.r(z.p(yga(this.data,c,b),function(){for(var a=m7(this.data.Ed(b,this.data.Ta)),e=0;e<a.length;e++)if(a[e].sd()==c){z.eb(a,e);break}d8(this,z.Nca,this.data.Ed(b,this.data.Ta),{replyId:c});this.wG.O((0,z.H)("The reply has been dismissed."),z.SW)},this),z.yM(this.Wu,(0,z.H)("Sorry, we couldn’t hide the reply. Please try again later and make sure you are logged in.")))};
z.f.zX=function(a){a=a.target;var b=z.Hf(a,"notesItem");if(b){var c=b.getAttribute("data-note-id");c==this.Ah?z.az(a,function(a){return!!a.getAttribute("data-action")||z.ud(a,"editable")},b,!0)==b&&j8(this,null):(j8(this,c),w8(this,c,{scroll:!0,dk:!0}))}};z.f.$Y=function(){var a=this.getSelection();j8(this,null);a&&g8(this,a.highlight);l8(this,a||this.data.Ta);this.me&&(a&&r8(this,{scroll:!0,dk:!0}),n8(this))};
z.f.AE=function(a){(a=a.target.getAttribute("name"))&&z7(this.anchors,a)&&S7(this.Kd,a,a==this.data.Ta)};z.f.Rp=function(){if(this.Ql){if(this.sf)return z.T(Error("UpdatePositions called after dispose"));m8.H.Rp.call(this);var a={scroll:!1,dk:!0};this.Ah?w8(this,this.Ah,a):u8(this,a)}};z.f.c4=function(){if(this.data.Ta){var a=this.anchors.get(this.data.Ta);if(!a)h8(this,null);else if(!this.ne.Rl){var b=z.wp();b&&(b=z.uo(b),z.tf(a,b)||h8(this,null))}}};
z.f.ha=function(){this.Za.unsubscribe("resize-end",this.hy,this);this.Za.unsubscribe("inner-resize-end",this.hy,this);this.Sc&&this.Sc.unsubscribe("highlight",this.tM,this);m8.H.ha.call(this)};z.n(z8,z.ho);z8.prototype.EG=function(a,b,c,d){return new m8(a.xa(),b,c,d)};z.n(A8,z.CA);z.f=A8.prototype;z.f.$t=0;z.f.FE=0;z.f.nk=0;z.f.aD=0;z.f.by=0;z.f.SL=0;z.f.oo=0;z.f.gF=1;z.f.Xy=0;z.f.Wy=0;z.f.fN=0;z.f.fi=void 0;z.f.Ua=[];z.f.bt=function(){this.Ua.length||(this.Ua=[z.Oy(this.$b,"touchstart",this.jZ,this),z.Oy(this.$b,"touchmove",this.zE,this),z.Oy(this.$b,"touchend",this.iZ,this)])};
z.f.jZ=function(a){var b=this.$b.firstChild;this.aD=this.nk=0;this.fN=b.offsetWidth*this.$b.children.length;this.fi=void 0;this.Xy=this.$b.offsetWidth;this.gF=1;this.SL=-(this.$b.children.length-1);this.oo=+new Date;this.$t=a.touches[0].pageX;this.FE=a.touches[0].pageY;z.Rp(this.$b,"transition-duration",0)};
z.f.zE=function(a){1<a.touches.length||(this.nk=a.touches[0].pageX-this.$t,this.aD=a.touches[0].pageY-this.FE,this.$t=a.touches[0].pageX,this.FE=a.touches[0].pageY,"undefined"==typeof this.fi&&(this.fi=Math.abs(this.aD)>Math.abs(this.nk)),this.fi||(this.by=this.nk/this.gF+B8(this),a.preventDefault(),this.gF=0===this.Wy&&0<this.nk?this.$t/this.Xy+1.25:this.Wy==this.SL&&0>this.nk?Math.abs(this.$t)/this.Xy+1.25:1,z.Rp(this.$b,"transform","translate3d("+this.by+"px,0,0)")))};
z.f.iZ=function(){if(!this.fi){var a=1E3>+new Date-this.oo&&15<Math.abs(this.nk)?0>this.nk?-1:1:0,b=Math[a?0>this.nk?"ceil":"floor":"round"](B8(this)/(this.fN/this.$b.children.length)),b=Math.min(b+a,0),b=Math.max(-(this.$b.children.length-1),b);C8(this,b,".2s")}};z.f.disable=function(){z.Rp(this.$b,"transition-duration","0");z.Rp(this.$b,"transform","translate3d(0,0,0)");z.Py(this.Ua);this.Ua=[]};z.f.enable=A8.prototype.bt;z.n(D8,a8);z.f=D8.prototype;z.f.ha=function(){this.mM=null;this.$b&&(this.$b.disable(),this.$b.unsubscribe("slide",this.xM,this),this.$b=null);this.Ag&&(this.Ag.cancel(),this.Ag=null);D8.H.ha.call(this)};z.f.Lu=function(){D8.H.Lu.call(this);l7(this.bD,!0)};z.f.MG=function(){l7(this.bD,!1);D8.H.MG.call(this)};
z.f.qI=function(){this.Tu=null;var a=(0,z.Jq)(),b=z.FX();this.Rp();if(this.isAuthenticated){var c=this.data.gm.userId===z.Fj().userId;z.Cd(this.Ic,"is-notesCreator",c)}z.h6(this.query(".js-notesPostCreator"),this.data.gm.name);this.Cz(b);z.Yz("notes.renderMarkers",(0,z.Jq)()-a)};z.f.Cz=function(a){a.Qf&&this.Kd.kf[a.Qf]&&a.noteId&&this.data.Ed(a.noteId,a.Qf)&&F8(this,a.Qf)};z.f.SQ=function(){};
z.f.TQ=function(a){this.kJ(a);z.u(this.ln,"is-showingNotesReplies");this.$b.disable();s7(this.Wi,{Em:this.Em,DI:this.data.gm,cn:window.Infinity})};z.f.rI=function(a){a=a.value;this.Kd.kf[a]&&(a==this.data.Ta?h8(this,null):F8(this,a))};z.f.aB=function(a){this.Kd.zw(a.tc());if(!this.data.Ta||!Q7(this.data,this.data.Ta).rb())return this.rE();C8(this.$b,0,"0")};z.f.aY=function(){E8(this,!0)};z.f.sM=function(a){this.data.Ta&&!z.tf(this.Ic,a.target)&&(a.stopPropagation(),this.rE())};
z.f.xM=function(a){if(a=Q7(this.data,this.data.Ta).Qo(a)){j8(this,a.eb());if(!a.Ki()){a=a.tc();var b=this.anchors.get(a),b=z.Wy(b);g8(this,new z.dk({anchor:a,startIndex:0,endIndex:b.length-1,content:b}),!0)}E8(this,!0)}};
z.f.rE=function(){z.ud(this.ln,"is-showingNotesReplies")?z.ud(this.ln,"is-showingNotesReplies")&&(z.u(this.Ic.querySelector(".is-activeNote .notesReplies"),"notesReplies--hidden"),z.v(this.ln,"is-showingNotesReplies"),this.$b.enable(),C8(this.$b,0,"0",!0),E8(this,!1),s7(this.Wi,{Em:this.Em,DI:this.data.gm,cn:this.cn})):z.p(h8(this,null),function(){z.v(this.ln,"is-showingNotesReplies");z.v(this.ln,"is-newNoteEditorActivated");z.v(this.Lf,"is-showingNewNoteEditor");z.v(this.screen.aa(),"is-notesListVisible");
l7(this.bD,!1);this.Vy&&z.kf(this.Vy);this.$b.disable();this.Rp()},this)};z.n(G8,z.ho);G8.prototype.EG=function(a,b,c){return new D8(a.xa(),b,c)};z.n(H8,z.ho);z.f=H8.prototype;z.f.load=function(){this.zd||(this.zd=z.p(this.Ba.Qj(this.Ga),this.PV,this));return this.zd.Db()};z.f.toggle=function(a,b,c,d){var e=L8(this,a,b,c);return e&&e.ua()==z.Fj().userId?this.remove(e):e&&d?J8(this,a,e.Vb(),e.zc(),!d):J8(this,a,b,c,!0)};z.f.s2=function(a,b,c){var d=K8(this,a,b,c);return d?z.od(d):(d=L8(this,a,b,c))?J8(this,a,d.Vb(),d.zc(),!1):J8(this,a,b,c,!0)};
z.f.create=function(a,b,c,d,e){if(e){for(;" "==z.Ot(a,b)&&c>b+1;)b++;for(;" "==z.Ot(a,c-1)&&c>b+1;)c--}return z.p(this.Ky.post(z.w(this.L,z.Y4,{postId:this.Ga}),{paragraphs:[a.lb().Hb()],startOffset:b,endOffset:c,quoteType:d},{json:!0}),function(a){return z.pC(this.ga,z.xk(a.value))},this)};z.f.remove=function(a){this.pj.remove(a);this.ga.remove(a);return z.p(this.Ky.ge(z.w(this.L,z.mba,{postId:this.Ga,quoteId:a.Xe()})),function(){return a},this)};
z.f.PV=function(a){z.mC(this.ga,a);a=(a.value||[]).filter(this.$W,this);this.pj.addAll(a);return this.pj};z.f.$W=function(a){var b=a.ob()[0],c=new z.ll(Gga(a));if(b.W()==c.W())return!0;var b=b.W().substring(a.startOffset,a.endOffset),d=c.W().indexOf(b);return-1<d?(a.startOffset=d,a.endOffset=d+b.length,a.paragraphs=[c],!0):!1};z.f.ON=function(){this.Nq=M8(this,this.pj.ad())};z.n(N8,z.EA);z.f=N8.prototype;z.f.ng=function(){return this.li.ng()};z.f.V=function(){N8.H.V.call(this);z.FA(this,this.vD,"data-redirect-type-quote",this.IX,this);this.listen(this.qc,"click",this.Gt,this);z.jX(this.tb)&&z.Ly()&&this.listen(this.qc,"mouseover",this.YV,this);z.r(this.fc.load(),z.T);var a=this.ng();a&&(z.FA(this,a,"quote",this.TV,this),z.FA(this,a,"quote-respond",this.UV,this),z.FA(this,a,"show",this.RF,this),z.FA(this,a,"hide",this.fY,this))};
z.f.IX=function(a){var b=z.eX(this.li,this.ng().qo);b&&(a.url=new z.Jd(z.w(this.L,z.nba,{postId:this.tb.$()},{paragraphs:JSON.stringify([b.Or.lb().Hb()]),startOffset:b.start,endOffset:b.end})))};z.f.Gt=function(a){z.az(a.target,function(a){if(a===this.qc)return!0;var c=z.cD(a);if(3==c)return!0;if(7==c){if(c=S8(this,a))if(Q8(this,c),z.Ly())U8(this,c);else{var d=new z.VS;O8(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.YV=function(a){z.az(a.target,function(a){if(a===this.qc)return!0;var c=z.cD(a);if(3==c)return!0;if(7==c){c=z.wp();if(!(c&&!c.isCollapsed()||this.ng()&&this.ng().pp())&&(c=S8(this,a))){var d=this.qc.querySelector('.markup--quote[name~\x3d"'+c.Xe()+'"]');a=new z.rY(a,100);O8(this,c,d,a);Q8(this,c)}return!0}return!1}.bind(this))};
z.f.RF=function(){var a=z.wp();a&&!a.isCollapsed()&&Q8(this,null);if(z.jX(this.tb)&&(a=z.eX(this.li,this.ng().qo))){var a=K8(this.fc,a.Or,a.start,a.end),b=this.ng().fa().querySelector(".js-highlightMenuQuoteButton");z.Cd(b,"is-active",!!a)}};z.f.fY=function(){this.Kk&&Q8(this,null)};
z.f.TV=function(){if(z.jX(this.tb)){var a=z.dH(this.ng());if(a){var b=a.range,c=a.G3,a=this.ng().fa().querySelector(".js-highlightMenuQuoteButton"),d=z.ud(a,"is-active"),b=z.eX(this.li,b);z.r(z.p(this.fc.toggle(b.Or,b.start,b.end,!c),function(a){z.Bp();d?z.hH(this.ng()):U8(this,a);var b=c?"selection_menu":"quote_click_menu";V8(this,a.Xe(),!d,b)},this),z.T)}}};
z.f.UV=function(){if(z.kX(this.tb)){var a=z.dH(this.ng());a&&(a=z.eX(this.li,a.range),z.r(z.p(this.fc.create(a.Or,a.start,a.end,1,!0),function(a){V8(this,a.Xe(),!0,"selection_menu_quote_respond");this.wa.navigate(z.w(this.L,z.Ix,{},{inResponseToQuoteId:a.quoteId}))},this),z.T))}};
z.f.cW=function(a){var b=this.Kk,c=R8(this,b),d=b.Vb(),e=b.zc(),b=a.query(".js-quoteAttributions-pileOn"),g=z.ud(b,"is-active");z.r(z.p(this.fc.toggle(c,d,e,!0),function(b){var k=a.query(".js-quoteAttributions-pileOn");z.Dd(k,"is-active");if(k=L8(this.fc,c,d,e)){var m=P8(this,k),q=a.query(".js-quoteAttributions-info");z.Gy(q,K7,m)}else a.nb();!g&&z.Ly()&&(a.nb(),U8(this,k));k=z.Ly()?"quote_hover":"quote_click_mobile";V8(this,b.Xe(),!g,k)},this),z.T)};
z.f.dW=function(){if(z.kX(this.tb)){var a=R8(this,this.Kk),b=this.Kk.Vb(),c=this.Kk.zc();z.r(z.p(this.fc.create(a,b,c,1,!0),function(a){V8(this,a.Xe(),!0,"quote_respond");this.wa.navigate(z.w(this.L,z.Ix,{},{inResponseToQuoteId:a.quoteId}))},this),z.T)}};
z.f.YM=function(){var a=new Y7(this.qc),b=this.fc.Nq,c=Object.keys(b).concat(this.PK);z.ob(c);c.forEach(function(a){var c=b[a]||[],g=this.tb;if(g=(a=g.qc&&z.sz(g.qc,a))&&this.tb.og(a))jga(g,c),a.innerHTML=z.Uw(g,z.x,z.MD)},this);this.PK=Object.keys(b);(a=a.restore())&&a.select()};W8.prototype.X1=function(a,b){return new N8(this.ca,a,b)};var X8=z.vU;X8.xa().scope("screen").add("notes",z8).add("notes-mobile",G8).add("quotes",W8);z.e6(X8,"notes");}).call(this, _mdm);
